### ISSUE TITLE
Login form fallback method

### ISSUE THREAD

**Issue by DylanDonkersgoed** [gssapi/mod_auth_gssapi#239] opened 2020-10-15 14:56 UTC
I would like to use this module but fall back to a login form. So the user would be SSO authenticated via GSSAPI if possible but have the option to enter their credentials into a form if they were not and authenticate to the kerberos backend that way. What's the best way to configure this?

I saw the discussion in https://github.com/gssapi/mod_auth_gssapi/issues/104 but I didn't want to derail the enhancement proposal. I see a few possible alternate solutions suggested on that issue, e.g.:

https://github.com/gssapi/mod_auth_gssapi/issues/104#issuecomment-244199829
https://github.com/gssapi/mod_auth_gssapi/issues/104#issuecomment-315986583

but I don't have enough background knowledge about this to fill in the blanks.

**Comment by simo5** [comment] 2020-10-15 16:08
The best way to configure a fallback login form is to provide it as part of the 401 reply, browsers will attempt to complete negotiation if there is an accompaining negotiate header, or fall back to show the 401 page.
In general I would look at how the FreeIPA project handles this as they have it all figured out already, including logging out and using login form out even if you actually do have krb5 credentials available.

At any rate, I consider this fundamentally a duplicate of #104 so I am going to close this issue.

**Closed by simo5** 2020-10-15 16:08 UTC
Labels: duplicate, question
