### ISSUE TITLE
ntlmsspi not sending www-authenticate?

### ISSUE THREAD

**Issue by LukasK07** [gssapi/mod_auth_gssapi#220] opened 2020-07-20 10:12 UTC
Hi team,
i'm occuring an error with following setup:
- Windows Active Directory Domain
- RHEL (7.6)
- Apache httpd 2.4.6-89.el7_6.1
- mod_auth_gssapi.x86_64 (v 1.5.1-5.el7

I'm trying to use httpd as a proxy for authentication of users against Active Directory. 

I managed to get krb5 configuration working fine, but i'm facing problems with using ntlmssp, by httpd conf. looks the following:
```
<Location /location>
Authtype GSSAPI
AuthName "my name..."
GssapiAllowedMech ntlmssp
GssapiCredStore keytab:/etc/keytab.keytab # obsolete for ntlm...
GssapiConnectionBound On
</Location>
```

I tried different scenarios and found following (maybe) problem:
- with the configuration shown above, the first response from the server is not returning any WWW-Authenticate header. Other responses are returning Negotiate. From my understand the client tries now **not to authenticate** with any method. With a krb5 configuration the clients receives an authentication header and authentication works fine.

Any suggestions or ideas on my problem?

**Comment by simo5** [comment] 2020-07-20 14:25
I assume you are using gssntlmssp on your system to handle NTLMSSP authentication ?
If not I would expect mod_auth_gssapi to not find any ntlmssp provider and not return any auth header.

**Comment by LukasK07** [comment] 2020-07-20 17:51
Thanks for response, yes i do (at least i'm trying)

i followed the instructions provided:
- installed latest gssntlmssp .rpm
- set environmental variable for the  user/pswd file (for httpd service)
- created user/pswd file

Am i'm missing something?

**Comment by simo5** [comment] 2020-07-20 18:11
In order to authenticate against Active Directory you need to use gssntlmssp windbindd integration(but see https://github.com/gssapi/gss-ntlmssp/pull/33) , however you can have it work with a user file as well if you are ok copying credentials over to the server for any user that needs access to it.

I guess seeing if there is anything in the apache logs (after turning debug on) may help

**Comment by simo5** [comment] 2020-08-05 16:53
Closing as it seem this is getting no feedback, and the problem seems clearly not a bug in mod_auth_gssapi

**Closed by simo5** 2020-08-05 16:53 UTC
